name: 'Storybook Tests'
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook:nx-storybook-ngzorro --quiet
      - name: Serve storybook and run test
        run: npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npx http-server dist/storybook/nx-storybook-ngzorro --port 6006 --silent" "npx wait-on tcp:6006 && npm run test-storybook"
